### ISSUE TITLE
setting volumes hostpath causes RunContainerError and/or kube-solo VM crash

### ISSUE THREAD

**Issue by bw2** [TheNewNormal/kube-solo-osx#173]
Hi, I'm trying to deploy a mongo container to kube-solo on MacOSX (v10.11.6).
It works as expected until I add a volume with hostPath as below. This leads to the pod not starting (status RunContainerError), and (after several modifications to the hostPath directory and restart attempts) causes kube-solo VM to crash, requiring a Setup > Destroy VM, Init VM cycle.
The hostPath directory exists and has 777 permissions. 

```
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: mongo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: mongo
    spec:
      volumes:
      - name: mongo-dbpath
        #emptyDir: {}
        hostPath:
          path: /usr/local/var/mongo
      containers:
      - name: mongo-pod
        image: mongo:latest
        ports:
        - containerPort: 27017
          protocol: TCP
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: mongo-dbpath
          mountPath: /data/db
      restartPolicy: Always
      dnsPolicy: ClusterFirst
```
